config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'current_rev', to: 'home#current_rev'
  get 'test', to: 'application#test'

  mount(LetterOpenerWeb::Engine, at: '/letter_opener') if Rails.env.development?

  resources :rooms do
    resources :messages
  end

  

  # around login, sign_up, logout
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  get 'activate', to: 'users#activate'
  get 'sign_up', to: 'users#new', as: :sign_up
  post 'sign_up', to: 'users#create'

  # ユーザー設定の編集
  get '/users/settings/edit', to: 'users#edit_settings', as: 'edit_user_settings'
  patch '/users/settings/update', to: 'users#update_settings', as: 'update_user_settings'

  # ユーザープロフィールの編集
  get '/users/profile/edit', to: 'users#edit_profile', as: 'edit_user_profile'
  patch '/users/profile/update', to: 'users#update_profile', as: 'update_user_profile'
  
  resources :users do
    collection do
      resources :friendships, only: [:index, :create, :destroy]
    end
  end

  # to avoid catch active_storage routes
  match '*not_found_path' => 'home#not_found', via: :all, constraints: -> { _1.path.exclude? 'rails/active_storage' }
end

app/models/user.rb
# frozen_string_literal: true

# app/models/user.rb

class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :messages

  has_many :friendships
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"

  has_many :friends, through: :friendships, source: :friend
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  has_and_belongs_to_many :rooms

  has_one_attached :icon

  validates :email, uniqueness: true
  validates :username, uniqueness: true
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit_settings, :update_settings, :edit_profile, :update_profile]
  def new
    @user = User.new
  end

  def show
    @user = if params[:id] == current_user.id.to_s
      current_user
    else
      current_user.friends.find(params[:id])
    end
  end

  def create
    @user = User.new(user_settings_params)
    if @user.save
      redirect_to(login_path, notice: "User was successfully created. Please check your email to activate.")
    else
      flash.now[:alert] = "Invalid email/password combination"
      render(:new)
    end
  end

  def activate
    if (user = User.load_from_activation_token(params[:token]))
      user.activate!
      auto_login(user)
      redirect_to(root_path, notice: "Your account has been activated successfully!")
    else
      redirect_to(root_path, alert: "Invalid activation code")
    end
  end

  def edit_settings
    @user = current_user
  end

  def update_settings
    @user = current_user
    if @user.update(user_settings_params)
      flash[:notice] = "Settings updated"
      redirect_to(@user)
    else
      flash[:alert] = "Failed to update settings"
      render(:edit_settings)
    end
  end

  def edit_profile
    @user = current_user
  end

  def update_profile
    @user = current_user
    if @user.update(user_profile_params)
      flash[:notice] = "Profile updated"
      redirect_to(@user)
    else
      flash[:alert] = "Failed to update profile"
      render(:edit_profile)
    end
  end

  private

  def user_settings_params
    params.require(:user).permit(:email, :password, :username)
  end

  def user_profile_params
    params.require(:user).permit(:biography, :birthday, :icon)
  end

  # beforeフィルタ

  # ログイン済みユーザーかどうか確認
  def logged_in_user
    unless logged_in?
      flash[:alert] = "Please log in."
      redirect_to(login_url, status: :see_other)
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  # 引数で与えられたユーザーのGravatar画像返す
  def gravatar_for(user, options = { size: 80 })
    size         = options[:size]
    gravatar_id  = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Update your settings</h1>

<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user) do |f| %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/edit_profile.html.erb
<h1>Update your profle</h1>

<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: update_user_profile_path, method: :patch) do |f| %>

      <div class="d-flex">
        <%= f.file_field :icon, class: "w-auto border-0 form-control-sm" %>
        <%= render_user_icon(@user) if @user.icon.attached? %>
      </div>
        
      <%= f.label :birthday %>
      <%= f.date_field :birthday, class: 'form-control' %>
  
      <%= f.label :biography %>
      <%= f.text_area :biography, class: 'form-control', rows: "5" %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <%= link_to current_user do%>
      <button class="btn btn-secondary">
        <i class="bi bi-arrow-left"></i>
        Back
      </button>
    <% end %>
  </div>
</div>

app/views/users/edit_settings.html.erb
<h1>Update your settings</h1>

<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: update_user_settings_path, method: :patch) do |f| %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <%= link_to current_user do%>
      <button class="btn btn-secondary">
        <i class="bi bi-arrow-left"></i>
        Back
      </button>
    <% end %>
    
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_with model: @user, url: sign_up_path, class: 'form-group' do |form| %>
  <div class="mb-3">
    <%= form.label :email, class: 'form-label' %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :password, class: 'form-label' %>
    <%= form.password_field :password, class: 'form-control', autocomplete: 'new-password' %>
  </div>
  <div class="mb-3">
    <%= form.label :username, class: 'form-label' %>
    <%= form.text_field :username, class: 'form-control' %>
  </div>
  <%= form.submit "Sign Up", class: 'btn btn-primary' %>
<% end %>

app/views/users/show.html.erb
<div class="px-5">
  <div class="card p-3 d-flex flex-row" style="">
    <div class="card-img-div">
      <%= render_user_icon(@user, size: [120, 120]) %>
    </div>
    <div class="card-body">
      <div class="d-flex">
        <h2 class="card-title mx-auto"><strong><%= @user.username %></strong></h2>
        <% if current_user == @user %> 
          <%= link_to edit_user_settings_path do%>
            <h2 class="ms-auto"><i class="bi bi-gear" ></i></h2>
          <% end %>
        <% end %>
      </div>
      
      <p class="card-text"><%= @user.birthday %></p>
      <p class="card-text"><%= @user.biography %></p>
      <% if current_user == @user %>
        <%= link_to edit_user_profile_path do%>
          <button class="btn btn-primary">
            <i class="bi bi-pencil-square"></i>
            Edit Profile
          </button>
        <% end %>
      <% end %>
    </div>
  </div>
  <br>
  <% if current_user != @user %>
    <%= link_to friendships_path do%>
      <button class="btn btn-secondary">
        <i class="bi bi-arrow-left"></i>
        Back
      </button>
    <% end %>
  <% else %>
    <%= link_to root_path do%>
      <button class="btn btn-secondary">
        <i class="bi bi-arrow-left"></i>
        Back
      </button>
    <% end %>
  <% end %>
</div>