config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'current_rev', to: 'home#current_rev'
  get 'test', to: 'application#test'

  mount(LetterOpenerWeb::Engine, at: '/letter_opener') if Rails.env.development?

  resources :rooms do
    resources :messages
  end

  

  # around login, sign_up, logout
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  get 'activate', to: 'users#activate'
  get 'sign_up', to: 'users#new', as: :sign_up
  post 'sign_up', to: 'users#create'

  # ユーザー設定の編集
  get '/users/settings/edit', to: 'users#edit_settings', as: 'edit_user_settings'
  patch '/users/settings/update', to: 'users#update_settings', as: 'update_user_settings'

  # ユーザープロフィールの編集
  get '/users/profile/edit', to: 'users#edit_profile', as: 'edit_user_profile'
  patch '/users/profile/update', to: 'users#update_profile', as: 'update_user_profile'
  
  resources :users do
    collection do
      resources :friendships, only: [:index, :create, :destroy]
    end
  end

  # to avoid catch active_storage routes
  match '*not_found_path' => 'home#not_found', via: :all, constraints: -> { _1.path.exclude? 'rails/active_storage' }
end

app/models/friendship.rb
# frozen_string_literal: true

class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"

  validates :user_id, uniqueness: { scope: :friend_id }

  # ステータス値を定義
  enum status: { pending: 0, accepted: 10, declined: 90 }
end

app/controllers/friendships_controller.rb
# frozen_string_literal: true

class FriendshipsController < ApplicationController
  before_action :require_login

  def index
    @friends = current_user.friends
  end

  def create
    @friend = User.find_by(username: params[:username])
    if @friend && current_user.friends.append(@friend)
      respond_to do |format|
        format.html { redirect_to(friendships_path) }
        format.turbo_stream
      end
    else
      redirect_to(friendships_path, alert: "Unable to create friendship.")
    end
  end

  def destroy
    @user = User.find(params[:id])
    current_user.friendships.find_by(friend_id: @user.id).destroy
    respond_to do |format|
      format.html { redirect_to(friendships_path) }
      format.turbo_stream
    end
  end
end

app/views/friendships/_friend.html.erb
<%= turbo_frame_tag friend, class: 'd-flex' do %>
  <div class="mb-4 d-flex justify-content-evenly align-items-center">
    <%= link_to user_path(friend.id), data: { turbo_frame: "_top" }, class: "friendLink" do %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title d-flex justify-content-between">
            <%= friend.username %>
            <%= button_to '', friendship_path(friend.id), method: :delete, data: { turbo_confirm: 'Would you like to stop being friends?' }, class: 'btn-close m-0', onclick: "event.stopPropagation()" %>
          </h5>
          <p class="card-text"><%= friend.email %></p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/friendships/_friends.html.erb
<% friends.each do |friend| %>
  <%= render 'friend', friend: friend %>
<% end %>

app/views/friendships/create.turbo_stream.erb
<%= turbo_stream.prepend 'friends', partial: 'friendships/friend', locals: { friend: @friend } %>

app/views/friendships/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@user) %>

app/views/friendships/index.html.erb
<h1>Friends</h1>

<%= form_with url: friendships_path, method: :post, data: { turbo_frame: "new_friend" } do |form| %>
  <div class="mb-3">
    <%= form.label :username, class: 'form-label' %>
    <%= form.text_field :username, class: 'form-control', required: true %>
  </div>
  <%= form.submit 'Add Friend', class: 'btn btn-primary' %>
<% end %>

<div id="friends">
  <%= turbo_frame_tag "friends", class: 'd-flex w-100 flex-wrap justify-content-between', data: { turbo_action: :advance } do %>
    <%= render 'friends', friends: @friends %>
  <% end %>
</div>

<%= link_to root_path do%>
  <button class="btn btn-secondary">
    <i class="bi bi-arrow-left"></i>
    Back
  </button>
<% end %>