config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'current_rev', to: 'home#current_rev'
  get 'test', to: 'application#test'

  mount(LetterOpenerWeb::Engine, at: '/letter_opener') if Rails.env.development?

  resources :rooms do
    resources :messages
  end

  

  # around login, sign_up, logout
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  get 'activate', to: 'users#activate'
  get 'sign_up', to: 'users#new', as: :sign_up
  post 'sign_up', to: 'users#create'

  # ユーザー設定の編集
  get '/users/settings/edit', to: 'users#edit_settings', as: 'edit_user_settings'
  patch '/users/settings/update', to: 'users#update_settings', as: 'update_user_settings'

  # ユーザープロフィールの編集
  get '/users/profile/edit', to: 'users#edit_profile', as: 'edit_user_profile'
  patch '/users/profile/update', to: 'users#update_profile', as: 'update_user_profile'
  
  resources :users do
    collection do
      resources :friendships, only: [:index, :create, :destroy]
    end
  end

  # to avoid catch active_storage routes
  match '*not_found_path' => 'home#not_found', via: :all, constraints: -> { _1.path.exclude? 'rails/active_storage' }
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  attr_accessor :user_ids # for form
  attr_accessor :retention_hours # for room

  # Roomを消したときに、そのRoomに紐づくMessageも一緒に消えるようにする
  has_many :messages, dependent: :destroy

  has_and_belongs_to_many :users
  has_one_attached :image

  after_create_commit do |room|
    room.users.pluck(:id).each do |user_id|
      broadcast_prepend_to "user_#{user_id}_rooms", partial: "rooms/room", target: "user_#{user_id}_rooms"
    end
  end
  after_update_commit do |room|
    room.users.pluck(:id).each do |user_id|
      broadcast_prepend_to "user_#{user_id}_rooms", partial: "rooms/room", target: "user_#{user_id}_rooms"
    end
  end
  before_destroy do |room|
    room.users.pluck(:id).each do |user_id|
      broadcast_remove_to "user_#{user_id}_rooms"
    end
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @room = current_user.rooms.find(params[:id])
    # nilだった場合は、すべてのメッセージを表示
    @messages = if @room.retention_minutes.present?
      @room.messages.where("created_at >= ?", @room.retention_minutes.minutes.ago)
    else
      @room.messages
    end
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    # 選択されたフレンドと自分を紐づけてroomを作る
    @room = Room.new(room_params)
    @users = current_user.friends.where(id: room_user_params[:user_ids])
    @room.users.append([current_user, *@users])

    total_minutes = (@room.retention_hours.to_i * 60) + @room.retention_minutes.to_i
    @room.retention_minutes = total_minutes

    respond_to do |format|
      if @room.save
        format.html { redirect_to(room_url(@room), notice: "Room was successfully created.") }
        format.json { render(:show, status: :created, location: @room) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @room.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to(room_url(@room), notice: "Room was successfully updated.") }
        format.json { render(:show, status: :ok, location: @room) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @room.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to(root_url, notice: "Room was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:name, :retention_minutes, :retention_hours, :image)
  end

  def room_user_params
    params.require(:room).permit(user_ids: [])
  end
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
  def my_room_list_stream
    "user_#{current_user.id}_rooms"
  end

  def format_date(created_time)
    current_date = Time.now.in_time_zone.to_date
    if created_time.to_date == current_date
      # 今日の場合、hh:mm形式で出力
      created_time.strftime("%H:%M")
    else
      # それ以外の場合、mm/dd形式で出力
      created_time.strftime("%m/%d")
    end
  end
end

app/views/rooms/_form.html.erb
<%= turbo_frame_tag dom_id(Room.new), target: "_top" do %>
  <%= form_with(model: room) do |form| %>
    <% if room.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

        <ul>
          <% room.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control'%>
    
    <!-- 保持期間設定フィールド -->
    <div class="field">
      <%= form.label :retention_hours %>
      <%= form.number_field :retention_hours, in: 0..720, step: 1, value: 0, id: :room_retention_hours, class: 'form-control'%>
    </div>

    <div class="field">
      <%= form.label :retention_minutes %>
      <%= form.number_field :retention_minutes, in: 1..60, step: 1, value: 1, id: :room_retention_minutes, class: 'form-control'%>
    </div>

    <div class="field">
      <%= form.label :image %>
      <div class="d-flex">
        <%= form.file_field :image, class: "w-auto border-0 form-control-sm" %>
        <%= render_room_image(room) if room.image.attached? %>
      </div>
    </div>


    <div class="btn-group btn-group-vertical">
      <%= form.collection_check_boxes(:user_ids, current_user.friends, :id, :username) do |user| %>
        <%= user.label class: 'btn d-flex align-items-center' do%>
          <%= user.check_box %>
          <i class="bi bi-app"></i>
          <i class="bi bi-check2-square"></i>
          <span class="px-1"><%= user.text %></span>
        <% end %>
      <% end %>
    </div>
    
    <%= form.submit "#{room.persisted? ? "Update" : "Create"} Room", class: "btn btn-primary"  %>
  <% end %>
<% end %>

app/views/rooms/_room.html.erb
<%= turbo_frame_tag room do %>
  <%= link_to room, data: { turbo_frame: "_top" }, class: "roomLink" do %>
    <div class="card m-2 p-2 d-flex flex-row">
      <div class="card-img-div pt-2">
        <figure class="icon-circle">
          <%= render_room_image(room) %>
        </figure>  
      </div>
      <div class="card-body">
        <h4>
          <strong>RoomName:</strong>
          <%= room.name %>
        </h4>
        <div class="d-flex justify-content-between" id="latest-message"> 
          
          <% latest_message = room.messages.last %>
          <!-- retention_minutesが設定されていない場合の対処のため -->
          <% if room.retention_minutes %>
            <% retention_time = Time.now.in_time_zone - room.retention_minutes.minutes %>
          <% else %>
            <% retention_time = Time.now.in_time_zone - 100.years %>
          <% end %>

          <% if latest_message && latest_message.created_at > retention_time %>
            <h4>
              <%= latest_message.content %>
            </h4>
            <p>
              <%= format_date(latest_message&.created_at) %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>
<%= turbo_frame_tag "room" do %>
  <%= render 'form', room: @room %>
<% end %>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rooms</h1>

<div id="rooms">
  <% @rooms.each do |room| %>
    <%= render room %>
    <p>
      <%= link_to "Show this room", room %>
    </p>
  <% end %>
</div>

<%= link_to "New room", new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form", room: @room %>
    
    <%= link_to root_path do%>
      <button class="btn btn-secondary">
        <i class="bi bi-arrow-left"></i>
        Back
      </button>
    <% end %>
    
  </div>
</div>

app/views/rooms/show.html.erb
<%= turbo_stream_from @room %>

<!-- ルームアクション -->
<div id="message-features" class="d-flex flex-column">
    <%= turbo_frame_tag "room" do %>
      <div class="room-actions-container">
        <%= link_to root_path, "data-turbo-frame": "_top" do %>
          <button class="btn btn-outline-secondary btn-sm">
            <i class="bi bi-arrow-left"></i>
            Back
          </button>
        <% end %>
        <%= link_to 'Edit', edit_room_path(@room), class: "btn btn-outline-primary btn-sm", data: { turbo_frame: "_top" } %>
        <div class="actions-right">
          <%= button_to "Destroy this room", @room, method: :delete, class: "btn btn-outline-danger btn-sm", data: { turbo_confirm: "Would you like to delete this room?", turbo_frame: '_top' } %>
        </div>
      </div>
    <% end %>
  
  <!-- 保持期間表示、絶対位置指定でボタン群の右上に配置 -->
  <div class="d-flex justify-content-end mt-2">
    <% if @room.retention_minutes.present? %>
      <% hours = @room.retention_minutes / 60 %>
      <% minutes = @room.retention_minutes % 60 %>
      <span class="badge bg-secondary text-white">
        Message Expiration Time: 
        <span class="expiration-time"><%= sprintf('%02d:%02d:%02d', hours, minutes, 00) %></span>
    <% else %>
      <span class="badge bg-secondary text-white">Message Expiration Time: -</span>
    <% end %>
  </div>

  <!-- メッセージリスト -->
  <div id="messages" class="border rounded messages-container mt-1 flex-grow-1">
    <%= render @messages %>
  </div>


  <!-- 新規メッセージ入力 -->
  <%= turbo_frame_tag dom_id(Message.new), src: new_room_message_path(@room), target: "_top" %>
</div>

<style>
.message-<%= current_user.id %> {
  background-color: hwb(120deg 30.02% 25.47%);
  border-radius: 7.5px;
  margin-bottom: 8px;
  padding: 6px 12px;
  max-width: 80%;
  word-wrap: break-word;
  float: right;
  clear: both;
}

.message_box:not(.message-<%= current_user.id %>) {
  background-color: #ffffff;
  border-radius: 7.5px;
  margin-bottom: 8px;
  padding: 6px 12px;
  max-width: 80%;
  float: left;
  clear: both;
  word-wrap: break-word;
}

.room-actions-container {
  display: flex;
  align-items: center;
}

.actions-right {
  margin-left: auto;
}
</style>