config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'current_rev', to: 'home#current_rev'
  get 'test', to: 'application#test'

  mount(LetterOpenerWeb::Engine, at: '/letter_opener') if Rails.env.development?

  resources :rooms do
    resources :messages
  end

  

  # around login, sign_up, logout
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  get 'activate', to: 'users#activate'
  get 'sign_up', to: 'users#new', as: :sign_up
  post 'sign_up', to: 'users#create'

  # ユーザー設定の編集
  get '/users/settings/edit', to: 'users#edit_settings', as: 'edit_user_settings'
  patch '/users/settings/update', to: 'users#update_settings', as: 'update_user_settings'

  # ユーザープロフィールの編集
  get '/users/profile/edit', to: 'users#edit_profile', as: 'edit_user_profile'
  patch '/users/profile/update', to: 'users#update_profile', as: 'update_user_profile'
  
  resources :users do
    collection do
      resources :friendships, only: [:index, :create, :destroy]
    end
  end

  # to avoid catch active_storage routes
  match '*not_found_path' => 'home#not_found', via: :all, constraints: -> { _1.path.exclude? 'rails/active_storage' }
end

app/views/layouts/_flash_message.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>G2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "turbo", type: "module" %>
  </head>
  <body>
    <nav class="navbar navbar-expand navbar-light bg-light sticky-top border-bottom">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">G2</a>
        <ul class="navbar-nav ms-auto">
          <% if logged_in? %>
            <li class="nav-item">
              <a class="nav-link" href="#"><%= current_user.email %></a>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', logout_path, class: 'nav-link', data: { turbo_method: :delete } %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Login', login_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Up', sign_up_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <br>
    <div class="container">
      <%= render 'layouts/flash_message' %>
      <%= yield %>
    </div>
  </body>
</html>